apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: viranova
spec:
  selector:
    app: viranova
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer