name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Digital Ocean Container Registry
      uses: docker/login-action@v1
      with:
        registry: registry.digitalocean.com
        username: _  # Digital Ocean CR uses a static username '_'
        password: ${{ secrets.DO_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: registry.digitalocean.com/viranova-container/viranovabackend:latest
        build-args: |
          SERVICE_ACCOUNT_ENCODED=${{ secrets.SERVICE_ACCOUNT_ENCODED }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
          POSTGRES_SSLMODE=${{ secrets.POSTGRES_SSLMODE }}
          QDRANT_LOCATION=${{ secrets.QDRANT_LOCATION }}
          LANGCHAIN_TRACING_V2=${{ secrets.LANGCHAIN_TRACING_V2}}
          LANGCHAIN_API_KEY=${{ secrets.LANGCHAIN_API_KEY}}
          LANGCHAIN_PROJECT=${{ secrets.LANGCHAIN_PROJECT}}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
